districts = [
    ('063', 'Ashburton District'),
    ('076', 'Auckland'),
    ('055', 'Buller District'),
    ('049', 'Carterton District'),
    ('032', "Central Hawke's Bay District"),
    ('069', 'Central Otago District'),
    ('067', 'Chatham Islands Territory'),
    ('060', 'Christchurch City'),
    ('072', 'Clutha District'),
    ('071', 'Dunedin City'),
    ('001', 'Far North District'),
    ('028', 'Gisborne District'),
    ('074', 'Gore District'),
    ('056', 'Grey District'),
    ('016', 'Hamilton City'),
    ('030', 'Hastings District'),
    ('012', 'Hauraki District'),
    ('042', 'Horowhenua District'),
    ('058', 'Hurunui District'),
    ('075', 'Invercargill City'),
    ('054', 'Kaikoura District'),
    ('003', 'Kaipara District'),
    ('043', 'Kapiti Coast District'),
    ('026', 'Kawerau District'),
    ('046', 'Lower Hutt City'),
    ('065', 'Mackenzie District'),
    ('039', 'Manawatu District'),
    ('053', 'Marlborough District'),
    ('048', 'Masterton District'),
    ('015', 'Matamata-Piako District'),
    ('031', 'Napier City'),
    ('052', 'Nelson City'),
    ('033', 'New Plymouth District'),
    ('027', 'Opotiki District'),
    ('018', 'Otorohanga District'),
    ('040', 'Palmerston North City'),
    ('044', 'Porirua City'),
    ('070', 'Queenstown-Lakes District'),
    ('038', 'Rangitikei District'),
    ('024', 'Rotorua District'),
    ('036', 'Ruapehu District'),
    ('062', 'Selwyn District'),
    ('035', 'South Taranaki District'),
    ('019', 'South Waikato District'),
    ('050', 'South Wairarapa District'),
    ('073', 'Southland District'),
    ('034', 'Stratford District'),
    ('041', 'Tararua District'),
    ('051', 'Tasman District'),
    ('021', 'Taupo District'),
    ('023', 'Tauranga City'),
    ('011', 'Thames-Coromandel District'),
    ('064', 'Timaru District'),
    ('045', 'Upper Hutt City'),
    ('013', 'Waikato District'),
    ('059', 'Waimakariri District'),
    ('066', 'Waimate District'),
    ('017', 'Waipa District'),
    ('029', 'Wairoa District'),
    ('068', 'Waitaki District'),
    ('020', 'Waitomo District'),
    ('047', 'Wellington City'),
    ('022', 'Western Bay of Plenty District'),
    ('057', 'Westland District'),
    ('025', 'Whakatane District'),
    ('037', 'Whanganui District'),
    ('002', 'Whangarei District')
 ]
ALLOWED_DISTRICT_CODES = {code for code, _ in districts}
constraint_factors = [
    ('rivers', 'Rivers'),
    ('lakes', 'Lakes'),
    ('coastlines', 'Coastlines'),
    ('residential', 'Residential areas'),
]
ALLOWED_CONSTRAINTS = [code for code, _ in constraint_factors]
ALLOWED_SUITABILITY = ["slope","roads","powerlines","solar","temperature"]