[project]
name = "titiler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "titiler-core>=0.23.1",
    "uvicorn>=0.35.0",
]
