// This file is auto-generated by @hey-api/openapi-ts

export type AdminMapTaskResp = {
	error?: number;
	data?: MapTaskDetails | null;
};

export type AdminUpdateUserStatusRequest = {
	user_id: number;
	status: UserStatus;
};

export type BaseResp = {
	error?: number;
};

export type Body_Auth_user_login = {
	grant_type?: string | null;
	username: string;
	password: string;
	scope?: string;
	client_id?: string | null;
	client_secret?: string | null;
};

export type ConstraintFactor = {
	kind: string;
	value: number;
};

export type CreateMapTaskReq = {
	name: string;
	district_code: string;
	constraint_factors: Array<ConstraintFactor>;
	suitability_factors: Array<SuitabilityFactor>;
};

export type DistrictHistogram = {
	frequency: Array<number>;
	edges: Array<number>;
	min: number;
	max: number;
};

export type DistrictHistogramItem = {
	kind: string;
	histogram: DistrictHistogram;
};

export type DistrictHistogramsResp = {
	error?: number;
	list?: Array<DistrictHistogramItem>;
};

export type HTTPValidationError = {
	detail?: Array<ValidationError>;
};

export type MapTask = {
	id: number;
	name: string;
	user_id: number;
	user_email?: string | null;
	district_code: string;
	district_name?: string | null;
	status: number;
	status_desc?: string | null;
	started_at?: string | null;
	ended_at?: string | null;
	created_at: string;
};

export type MapTask4AdminPageData = {
	total?: number | null;
	current_page?: number | null;
	page_size?: number | null;
	error?: number;
	list?: Array<MapTask> | null;
};

export type MapTaskDetails = {
	id: number;
	name: string;
	user_id: number;
	user_email?: string | null;
	district_code: string;
	district_name?: string | null;
	status: number;
	status_desc?: string | null;
	started_at?: string | null;
	ended_at?: string | null;
	created_at: string;
	files?: Array<MapTaskFile>;
	constraint_factors?: Array<ConstraintFactor>;
	suitability_factors?: Array<SuitabilityFactor>;
};

export type MapTaskFile = {
	id: number;
	map_task_id: number;
	file_type: string;
	file_path: string;
	created_at: string;
};

export type MapTaskProgress = {
	id: number;
	map_task_id: number;
	percent: number;
	description?: string | null;
	phase?: string | null;
	error_msg?: string | null;
	created_at: string;
};

export type MapTaskProgressListResp = {
	error?: number;
	list: Array<MapTaskProgress>;
};

export type MyMapTaskListResp = {
	error?: number;
	list: Array<MapTaskDetails>;
};

export type MyMapTaskResp = {
	error?: number;
	data?: MapTaskDetails | null;
};

export type MyMapTaskTileSignature = {
	exp: number;
	task: number;
	sig: string;
};

export type MyMapTaskTileSignatureResp = {
	error?: number;
	data: MyMapTaskTileSignature;
};

export type OidcInfoResp = {
	login_url: string;
};

export type OidcTokenRequest = {
	code: string;
};

export type PostLoginResp = {
	access_token?: string | null;
	expires_in?: number | null;
	refresh_token?: string | null;
	token_type?: string | null;
	error?: number;
};

export type RegisterRequest = {
	email: string;
	password: string;
};

export type SelectOptionItem = {
	code: string;
	label: string;
};

export type SelectOptionListResp = {
	error?: number;
	list: Array<SelectOptionItem>;
};

export type SuitabilityFactor = {
	kind: string;
	weight: number;
	breakpoints: Array<number>;
	points: Array<number>;
};

export type Token = {
	access_token: string;
	token_type?: string;
};

export type User4Admin = {
	id?: number | null;
	provider?: string | null;
	sub?: string | null;
	email?: string | null;
	role?: number | null;
	status?: number | null;
	created_at?: string | null;
	last_login?: string | null;
};

export type User4AdminPageData = {
	total?: number | null;
	current_page?: number | null;
	page_size?: number | null;
	error?: number;
	list?: Array<User4Admin> | null;
};

export type UserPublic = {
	email: string;
	role?: number;
	status?: number;
	provider: string;
	sub: string;
	id: number;
};

export type UserStatus = 1 | 2;

export type ValidationError = {
	loc: Array<string | number>;
	msg: string;
	type: string;
};

export type AdminAdminGetUserListData = {
	currentPage?: number | null;
	keyword?: string | null;
	pageSize?: number | null;
	status?: number | null;
};

export type AdminAdminGetUserListResponse = User4AdminPageData;

export type AdminAdminUpdateUserStatusData = {
	requestBody: AdminUpdateUserStatusRequest;
};

export type AdminAdminUpdateUserStatusResponse = BaseResp;

export type AdminAdminGetMapTasksData = {
	currentPage?: number | null;
	name?: string | null;
	pageSize?: number | null;
	status?: number | null;
	userId?: number | null;
};

export type AdminAdminGetMapTasksResponse = MapTask4AdminPageData;

export type AdminAdminGetMapTaskData = {
	taskId: number;
};

export type AdminAdminGetMapTaskResponse = AdminMapTaskResp;

export type AdminAdminGetMapTaskProgressData = {
	taskId: number;
};

export type AdminAdminGetMapTaskProgressResponse = MapTaskProgressListResp;

export type AdminAdminInitializeInputDirectoryResponse = BaseResp;

export type AuthUserLoginData = {
	formData: Body_Auth_user_login;
};

export type AuthUserLoginResponse = Token;

export type AuthGetUserInfoResponse = UserPublic;

export type AuthUserRegisterData = {
	requestBody: RegisterRequest;
};

export type AuthUserRegisterResponse = UserPublic;

export type AuthGetOidcInfoResponse = OidcInfoResp;

export type AuthGetOidcTokenData = {
	requestBody: OidcTokenRequest;
};

export type AuthGetOidcTokenResponse = PostLoginResp;

export type AuthUserTokenRefreshResponse = PostLoginResp;

export type AuthUserLogoutResponse = BaseResp;

export type UserUserGetMyMapTasksData = {
	completed?: boolean | null;
};

export type UserUserGetMyMapTasksResponse = MyMapTaskListResp;

export type UserUserCreateMapTaskData = {
	requestBody: CreateMapTaskReq;
};

export type UserUserCreateMapTaskResponse = MyMapTaskResp;

export type UserUserGetMapTaskData = {
	taskId: number;
};

export type UserUserGetMapTaskResponse = MyMapTaskResp;

export type UserUserDeleteMapTaskData = {
	taskId: number;
};

export type UserUserDeleteMapTaskResponse = BaseResp;

export type UserUserCancelMapTaskData = {
	taskId: number;
};

export type UserUserCancelMapTaskResponse = BaseResp;

export type UserUserGetMapTaskTileSignatureData = {
	taskId: number;
};

export type UserUserGetMapTaskTileSignatureResponse =
	MyMapTaskTileSignatureResp;

export type UserUserDuplicateMapTaskData = {
	taskId: number;
};

export type UserUserDuplicateMapTaskResponse = BaseResp;

export type UserUserGetDistrictSelectOptionsData = {
	keyword?: string | null;
	limit?: number | null;
};

export type UserUserGetDistrictSelectOptionsResponse = SelectOptionListResp;

export type UserUserGetConstraintFactorsSelectOptionsData = {
	keyword?: string | null;
	limit?: number | null;
};

export type UserUserGetConstraintFactorsSelectOptionsResponse =
	SelectOptionListResp;

export type UserUserGetMapTaskProgressData = {
	taskId: number;
};

export type UserUserGetMapTaskProgressResponse = MapTaskProgressListResp;

export type UserUserGetDistrictHistogramsData = {
	districtCode: string;
	kind?: string | null;
};

export type UserUserGetDistrictHistogramsResponse = DistrictHistogramsResp;
