openapi: 3.0.3
info:
  title: "OpenAPI for Site Analyzer"
  version: "1.0.0"
servers:
  - url: "http://localhost:3000"
    description: "Development server"
paths:
  /v1/user-login:
    post:
      summary: "Login with Local Users"
      tags:
        - Auth
      description: "Logs in a user with local credentials."
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  minLength: 5
                password:
                  type: string
                  minLength: 8
              required:
                - email
                - password
      responses:
        "200":
          description: Successful login
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostLoginResp"
        "400":
          description: Bad request, invalid input
  /v1/user-register:
    post:
      summary: "Register a new user"
      tags:
        - Auth
      description: "Creates a new user account with the provided email and password."
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  minLength: 5
                password:
                  type: string
                  minLength: 8
                password2:
                  type: string
                  minLength: 8
              required:
                - email
                - password
                - password2
      responses:
        "200":
          description: Successful registration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BaseResp"
        "400":
          description: Bad request, invalid input
  /v1/oidc-info:
    get:
      summary: "Get OIDC Information"
      tags:
        - Auth
      responses:
        "200":
          description: Successful retrieval of OIDC information
          content:
            application/json:
              schema:
                type: object
                properties:
                  login_url:
                    type: string
                    description: The OIDC login URL
      security: []
  /v1/oidc-token:
    post:
      tags:
        - Auth
      summary: "Use code to get OIDC token"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                  description: The OIDC authorization code received after login
              required:
                - code
      responses:
        "200":
          description: Successful retrieval of OIDC token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostLoginResp"
      security: []
  /v1/user/token-refresh:
    post:
      summary: "Refresh user token"
      tags:
        - Auth
      responses:
        "200":
          description: Successful retrieval of user token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostLoginResp"
  /v1/user/logout:
    post:
      summary: "Logout user"
      tags:
        - Auth
      responses:
        "200":
          description: Successful logout
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BaseResp"
  /v1/user/my-map-tasks:
    get:
      summary: "Get user's map tasks"
      tags:
        - User
      parameters:
        - name: completed
          in: query
          description: "Filter for completed map tasks"
          required: false
          schema:
            type: boolean
      responses:
        "200":
          description: Successful retrieval of user's map tasks
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MyMapTaskListResp"
    post:
      summary: "Create a new map task"
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateMapTaskReq"
      responses:
        "200":
          description: Successful creation of map task
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MyMapTaskResp"
  /v1/user/my-map-tasks/{taskId}:
    get:
      summary: "Get user's map tasks"
      tags:
        - User
      parameters:
        - name: taskId
          in: path
          required: true
          description: "The ID of the map task"
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Successful retrieval of user's map tasks
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MyMapTaskResp"
  /v1/user/my-map-tasks/{taskId}/cancel:
    post:
      summary: "Cancel a map task"
      tags:
        - User
      parameters:
        - name: taskId
          in: path
          required: true
          description: "The ID of the map task to cancel"
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Successful cancellation of map task
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BaseResp"
components:
  schemas:
    BaseResp:
      type: object
      properties:
        error:
          type: integer
          description: 0 for success, other values for business errors
    LoginResult:
      type: object
      properties:
        access_token:
          type: string
          description: The OIDC access token
        expires_in:
          type: integer
          description: The number of seconds until the token expires
        refresh_token:
          type: string
          description: The OIDC refresh token
        token_type:
          type: string
          description: The type of the token
    PostLoginResp:
      allOf:
        - $ref: "#/components/schemas/BaseResp"
        - $ref: "#/components/schemas/LoginResult"
    MapTask:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: The unique identifier for the map task
        name:
          type: string
          description: The name of the map task
        user_id:
          type: integer
          format: int64
          description: The ID of the user who created the map task
        user_email:
          type: string
          format: email
          description: The email of the user who created the map task
        district_code:
          type: string
          description: The code of the district associated with the map task
        district_name:
          type: string
          description: The name of the district associated with the map task
        status:
          type: integer
          description: |
            The status of the map task.
            1: Created
            2: Processing
            3: Success
            4: Failure
            5: Cancelled
          enum: [1,2,3,4,5]
        started_at:
          type: string
          format: date-time
        ended_at:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
          description: The creation time of the map task
    MapTaskFile:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: The unique identifier for the map task file
        map_task_id:
          type: integer
          format: int64
          description: The ID of the associated map task
        file_type:
          type: string
          description: The type of the file
        file_path:
          type: string
          description: The path to the file
        created_at:
          type: string
          format: date-time
          description: The creation time of the map task file
    ConstraintFactor:
      type: object
      properties:
        kind:
          type: string
          description: The kind of constraint factor
        value:
          type: number
          description: The value of the constraint factor
      required:
        - kind
        - value
    SuitabilityFactorRange:
      type: object
      properties:
        start:
          type: number
          description: The start of the range for the suitability factor
        end:
          type: number
          description: The end of the range for the suitability factor
        points:
          type: integer
          description: The number of points in the range
      required:
        - start
        - end
        - points
    SuitabilityFactor:
      type: object
      properties:
        kind:
          type: string
          description: The kind of suitability factor
        weight:
          type: number
          description: The weight of the suitability factor
        ranges:
          type: array
          items:
            $ref: "#/components/schemas/SuitabilityFactorRange"
          description: List of ranges for the suitability factor
          minItems: 1
      required:
        - kind
        - weight
        - ranges
    MapTaskDetails:
      allOf:
        - $ref: "#/components/schemas/MapTask"
        - type: object
          properties:
            files:
              type: array
              items:
                $ref: "#/components/schemas/MapTaskFile"
            constraint_factors:
              type: array
              items:
                $ref: "#/components/schemas/ConstraintFactor"
              description: List of constraint factors for the map task
            suitability_factors:
              type: array
              items:
                $ref: "#/components/schemas/SuitabilityFactor"
              description: List of suitability factors for the map task
      
    MyMapTaskListResp:
      allOf:
        - $ref: "#/components/schemas/BaseResp"
        - type: object
          properties:
            list:
              type: array
              items:
                $ref: "#/components/schemas/MapTask"
    MyMapTaskResp:
      allOf:
        - $ref: "#/components/schemas/BaseResp"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/MapTaskDetails"
    CreateMapTaskReq:
      type: object
      properties:
        name:
          type: string
          description: The name of the map task
        district_code:
          type: string
          description: The code of the district associated with the map task
        constraint_factors:
          type: array
          items:
            $ref: "#/components/schemas/ConstraintFactor"
          description: List of constraint factors for the map task
        suitability_factors:
          type: array
          items:
            $ref: "#/components/schemas/SuitabilityFactor"
          description: List of suitability factors for the map task
      required:
        - name
        - district_code
        - constraint_factors
        - suitability_factors
                

  securitySchemes:
    OIDC:
      type: openIdConnect
      openIdConnectUrl: https://accounts.google.com/.well-known/openid-configuration
security:
  - OIDC: [user]
